In [12]:
#constant = big O(1)

In [14]:
#linear = An algorithm is said to take linear time, or O(n) time, if its time complexity is O(n). 
#Informally, this means that the running time increases at most linearly with the size of the input.
#i.e higher the input, more the time taken to complete the algorithm

In [103]:
n = 1000000

In [109]:
x = (n**4)
y = (3*(n**3)) + (2*(n**2)) + ((4*n)) + 1
print((y/x)*100)

0.0003000002000004


In [1]:
import math

In [14]:
math.log2(100)

6.643856189774724

In [15]:
#Recursion

In [20]:
def rec(n):
    if n>0:
        print(n**2)
        rec(n-1)

In [21]:
rec(4)

16
9
4
1


In [52]:
def rec(n):
    if n < 0:
        return 0
    return rec(n-1)+n
#n(n+1)/2

In [41]:
rec(10)

55

In [53]:
#Factorial with recurssion

In [64]:
def fac_rec(n):
    if n < 1:
        return 1
    return fac_rec(n-1)*n

In [66]:
fac_rec(3)

6

In [80]:
def linear_search(lst,key):
    for i in range(len(lst)):
        if lst[i] == key:
            return i

In [81]:
linear_search([1,2,3,4,5,6,7],3)

2

In [2]:
#Binary Search

In [10]:
def binary_iteration_search(lst,key):
    left = 0
    right = len(lst)-1
    while left <= right:
        middle = (left+right)//2
        if key == lst[middle]:
            return middle
        elif key < lst[middle]:
            right = middle - 1
        elif key > lst[middle]:
            left = middle + 1
    return 'Not Found'

In [11]:
binary_iteration_search([10,13,15,16,18,19,23,45,58,64,65,75,99],99)

12

In [15]:
#Selection sort

In [5]:
def selection_sort(a):
    n = len(a)
    mylist = []
    for i in range(n-1):
        position = i
        for j in range(i+1, n):
            if a[j] < a[position]:
                position = j
        a[i], a[position] = a[position], a[i]

In [10]:
a = [1,4,2,6,3,5]
selection_sort(a)

In [11]:
a

[1, 2, 3, 4, 5, 6]

In [1]:
#Insertion Sort

In [3]:
def insertion_sort(lst):
    indexing_length = range(1,len(lst))
    for i in indexing_length:
        value_to_sort = lst[i]
        while lst[i-1] > value_to_sort and i > 0:
            lst[i], lst[i-1] = lst[i-1], lst[i]
            i = i -1

In [4]:
lst = [8,7,6,5,4]
insertion_sort(lst)
print(lst)

[4, 5, 6, 7, 8]


In [42]:
#Insertion sort is coooooool

In [67]:
heros=['spider man','thor','hulk','iron man','captain america']

In [68]:
heros[1:3] = ['doctor strange']

In [69]:
heros

['spider man', 'doctor strange', 'iron man', 'captain america']

In [2]:
#😲😲😲😲😲😲😲😲😲😲😲😲😲😲😲😲😲😲😲😲😲😲😲😲😲😲😲😲😲😲😲😲😲
x = []
x[:] = '123456789'
print(x)

['1', '2', '3', '4', '5', '6', '7', '8', '9']


In [84]:
#Linked list Syntax

In [13]:
class Node:
    def __init__(self,element):
        self.element = element
        self.next = None
class LinkedList:
    def __init__(self):
        self.head = None
        self.tail = None
        self.size = 0
    def __len__(self):
        return self.size
    def isempty(self):
        return self.size == 0
    def add_last(self,value):
        newest = Node(value)
        if self.isempty():
            self.head = newest
        else:
            self.tail.next = newest
        self.tail = newest
        self.size += 1
    def search(self,key):
        index = 0
        p = self.head
        while p:
            if p.element == key:
                return index
            p = p.next
            index = index + 1
        return 'Not found'
    def add_first(self,value):
        newest = Node(value)
        if self.isempty():
            self.head = Newest
            self.tail = Newest
        else:
            newest.next = self.head
            self.head = newest
        self.size = self.size + 1
    def addany(self,value,position):
        newest = Node(value)
        p = self.head
        i = 1
        while i < position-1:
            p = p.next
            i = i+1
        newest.next = p.next
        p.next = newest
        self.size += 1 
    def display(self):
        p = self.head
        while p:
            print(p.element,end=' ')
            p = p.next
    def remove_first(self):
        if self.isempty():
            return 'No Element found in the list'
        p = self.head.element
        self.head = self.head.next
        self.size = self.size - 1
        if self.isempty():
            self.tail = None
        return p
    def remove_last(self):
        if self.isempty():
            return 'No Element found in the list'
        p = self.head
        i = 1
        while i < self.size - 1:
            p = p.next
            i = i + 1
        self.tail = p
        e = self.tail.next.element
        self.tail.next = None
        self.size = self.size - 1
        return e
    def remove_anywhere(self,position):
        p = self.head
        i = 1
        while i < position - 1:
            p = p.next
            i = i + 1
        e = p.next.element
        p.next = p.next.next
        self.size = self.size - 1
        return e
    def insertsorted(self,e):
        newest = Node(e)
        if self.isempty():
            self.head = newest
        else:
            p = self.head
            q = self.head
            while p and p.element < e:
                q = p
                p = p.next
            if p == self.head:
                newest.next = self.head
                self.head = newest
            else:
                newest.next = q.next
                q.next = newest
        self.size += 1

In [89]:
l = LinkedList()

In [90]:
l.add_last(7)
l.add_last(8)
l.add_last(9)
l.add_last(10)
l.add_last(11)

In [91]:
l.display()

7 8 9 10 11 

In [68]:
#Circular linked list

In [464]:
class Node:
    def __init__(self,element):
        self.element = element
        self.next = None
class Circular_linked_list:
    def __init__(self):
        self.head = None
        self.tail = None
        self.size = 0
    def __len__(self):
        return self.size
    def isempty(self):
        return self.size == 0
    def add_last(self,e):
        newest = Node(e)
        if self.isempty():
            newest.next = newest
            self.head = newest
        else:
            newest.next = self.tail.next#head
            self.tail.next = newest#tail 
        self.tail = newest
        self.size += 1
    def display(self):
        p = self.head
        for i in range(self.size):
            print(p.element, end=' ')
            p = p.next
    def add_first(self,e):
        newest = Node(e)
        if self.isempty():
            newest.next = newest
            self.head = newest
        else:
            self.tail.next = newest
            newest.next = self.head
        self.head = newest
        self.size += 1
    def add_any(self,value,position):
        newest = Node(value)
        p = self.head
        i = 1
        while i < position-1:
            p = p.next
            i = i+1
        newest.next = p.next
        p.next = newest
        self.size += 1 
    def remove_first(self):
        if self.isempty():
            return 'No element found'
        e = self.head.element
        self.tail.next = self.head.next
        self.head = self.head.next
        self.size -= 1
        if self.isempty():
            self.head = None
            self.tail = None
        return e
    def remove_last(self):
        if self.isempty():
            return 'No element found'
        p = self.head
        for i in range(1,self.size-1): 
            p = p.next
        self.tail = p
        p = p.next
        self.tail.next = self.head
        self.size = self.size - 1
        return p.element
    def remove_anywhere(self,position):
        p = self.head
        i = 1
        while i < position - 1:
            p = p.next
            i = i + 1
        e = p.next.element
        p.next = p.next.next
        self.size = self.size - 1
        return e

In [482]:
c = Circular_linked_list()

In [483]:
c.add_last(7)
c.add_last(8)
c.add_last(9)
c.add_last(10)
c.add_last(11)
c.add_last(12)

In [484]:
c.display()

7 8 9 10 11 12 

In [1]:
#Doubly linked list

In [314]:
class Node:
    def __init__(self, element, next = None, prev = None):
        self.element = element
        self.next = next
        self.prev = prev
class Doubly_linked_list:
    def __init__(self):
        self.head = None
        self.tail = None
        self.size = 0
    def __len__(self):
        return self.size
    def isempty(self):
        return self.size == 0
    def add_last(self,e):
        newest = Node(e)
        if self.isempty():
            self.head = newest
            self.tail = newest
        else:
            self.tail.next = newest
            newest.prev = self.tail
            self.tail = newest
        self.size += 1
    def display(self):
        p = self.head
        for i in range(self.size):
            print(p.element, end = ' ')
            p = p.next
    def display_rev(self):
        p = self.tail
        for i in range(self.size):
            print(p.element, end = ' ')
            p = p.prev
    def add_first(self,e):
        newest = Node(e)
        if self.isempty():
            self.head = newest
            self.tail = newest
        else:
            self.head.prev = newest
            newest.next = self.head
            self.head = newest
        self.size += 1
    def add_any(self,e,position):
        newest = Node(e)
        p = self.head
        for i in range(1, position-1):
            p = p.next
        newest.next = p.next
        p.next.prev = newest
        p.next = newest
        newest.prev = p
        self.size += 1
    def delete_first(self):
        if self.isempty():
            return 'No elements found'
        e = self.head.element
        self.head = self.head.next
        self.size = self.size - 1
        if self.isempty():
            self.tail = None
        else:
            self.head.prev = None
        return e
    def delete_last(self):
        if self.isempty():
            return 'No elements found'
        e = self.tail.element
        self.tail = self.tail.prev
        self.size = self.size - 1
        if self.isempty():
            self.head = None
        return e
    def remove_any(self,position):
        if self.isempty():
            return 'No elements found'
        p = self.head
        for i in range(1,position-1):
            p = p.next
        e = p.next.element
        p.next = p.next.next
        p.next.prev = p
        self.size -= 1
        return e

In [325]:
d = Doubly_linked_list()

In [326]:
d.add_last(7)
d.add_last(8)
d.add_last(9)
d.add_last(10)
d.add_last(11)

In [327]:
d.display()

7 8 9 10 11 

In [2]:
#Stacks with linked list (Last in first out)

In [248]:
class Node:
    def __init__(self, element):
        self.element = element
        self.next = None
class Linked_stack:
    def __init__(self):
        self.top = None
        self.size = 0
    def __len__(self):
        return self.size
    def isempty(self):
        return self.size == 0
    def push(self, value):
        newest = Node(value)
        if self.isempty():
            self.top = newest
        else:
            newest.next = self.top#Recently added items are heads cuz of Last in first out
            self.top = newest
        self.size += 1
    def pop(self):
        if self.isempty():
            return 'No elements found'
        e = self.top.element
        self.top = self.top.next
        self.size -= 1
        return e
    def top_element(self):
        if self.isempty():
            return 'No elements found'
        return self.top.element
    def display(self):
        p = self.top
        while p:
            print(p.element, end = ' ')
            p = p.next

In [249]:
s = Linked_stack()

In [250]:
s.push(7)
s.push(8)
s.push(9)
s.push(10)

In [251]:
s.display()

10 9 8 7 

In [1]:
#Queues using linked list(FIFO)

In [235]:
class _Node:
    __slots__ = 'element', 'next'
    def __init__(self, element, next = None):
        self.element = element
        self.next = next
class Queues:
    def __init__(self):
        self.front = None
        self.rear = None
        self.size = 0
    def __len__(self):
        return self.size
    def isempty(self):
        return self.size == 0
    def enqueue(self, e):
        newest = _Node(e)
        if self.isempty():
            self.front = newest
        else:
            self.rear.next = newest
        self.rear = newest
        self.size += 1
    def dequeue(self):                      
        if self.isempty():                       
            print('No elements found')
            return
        e = self.front.element                   
        self.front = self.front.next               
        self.size -= 1                            
        if self.isempty():                       
            self.rear = None                             
        return e                                         
    def first(self):
        if self.isempty():
            return 'No elements found'
        return self.front.element
    def display(self):
        p = self.front
        while p:
            print(p.element, end = ' ')
            p = p.next
        print()

In [236]:
q = Queues()

In [237]:
q.enqueue(7)
q.enqueue(8)
q.enqueue(9)
q.enqueue(10)

In [238]:
q.display()

7 8 9 10 


In [239]:
#Binary tree
#PREORDER = UP(root) - DOWN(left) - DOWN(right)
#INORDER = DOWN(left) - UP(root) - DOWN(right)
#POSTORDER = DOWN(left) - DOWN(right) - UP(root)
#LEVELORDER = ABCDEFG - (From first level to last level) using queues

In [261]:
class Node:
    def __init__(self, element, left=None, right=None):
        self.element = element
        self.left = left
        self.right = right
class Binary_tree:
    def __init__(self):
        self.root = None
    def maketree(self, element, left, right):
        self.root = Node(element, left.root, right.root)
    def preorder(self, troot):
        if troot:
            print(troot.element, end = ' ')
            self.preorder(troot.left)
            self.preorder(troot.right)
    def inorder(self, troot):
        if troot:
            self.inorder(troot.left)
            print(troot.element, end = ' ')
            self.inorder(troot.right)
    def postorder(self, troot):
        if troot:
            self.postorder(troot.left)
            self.postorder(troot.right)
            print(troot.element, end = ' ')
    def levelorder(self):
        q = Queues()
        t = self.root
        print(t.element, end=' ')
        q.enqueue(t)
        while not q.isempty():
            t = q.dequeue()
            if t.left:
                print(t.left.element, end=' ')
                q.enqueue(t.left)
            if t.right:
                print(t.right.element, end=' ')
                q.enqueue(t.right)
    def count(self,troot):
        if troot:
            x = self.count(troot.left)
            y = self.count(troot.right)
            return x + y + 1
        return 0
    def height(self,troot):
        if troot:
            x = self.height(troot.left)
            y = self.height(troot.right)
            if x > y:
                return x + 1
            else:
                return y + 1
        return 0

In [262]:
a = Binary_tree()
b = Binary_tree()
c = Binary_tree()
d = Binary_tree()
e = Binary_tree()
f = Binary_tree()
x = Binary_tree()

In [263]:
d.maketree(40, x, x)
f.maketree(60, x, x)
b.maketree(20, d, x)
e.maketree(50, x, f)
c.maketree(30, e, x)
a.maketree(10, b, c)

In [256]:
a.postorder(a.root)

40 20 60 50 30 10 

In [257]:
a.preorder(a.root)

10 20 40 30 50 60 

In [258]:
a.inorder(a.root)

40 20 10 50 60 30 

In [259]:
a.levelorder()

10 20 30 40 50 60 

In [260]:
a.count(a.root)

6

In [266]:
a.height(a.root)

4

In [267]:
#Binary Search Tree

In [324]:
class Node:
    def __init__(self, element, left=None, right=None):
        self.element = element
        self.left = left
        self.right = right

class Binary_search_tree:
    def __init__(self):
        self.root = None
    
    def insert(self, troot, e):
        temp = None
        while troot:
            temp = troot
            if e == troot.element:
                return
            elif e < troot.element:
                troot = troot.left
            elif e > troot.element:
                troot = troot.right
        newest = Node(e)
        if self.root:
            if e < temp.element:
                temp.left = newest
            elif e > temp.element:
                temp.right = newest
        else:
            self.root = newest
    
    def rec_insert(self,troot,e):
        if troot:
            if e < troot.element:
                troot.left = self.rec_insert(troot.left,e)
            elif e > troot.element:
                troot.right = self.rec_insert(troot.right,e)
        else:
            newest = Node(e)
            troot = newest
        return troot
    
    def search(self,key):
        troot = self.root
        while troot:
            if key == troot.element:
                return True
            elif key < troot.element:
                troot = troot.left
            elif key > troot.element:
                troot = troot.right
        return False
    
    def rsearch(self,troot,key):
        if troot:
            if key == troot.element:
                return True
            elif key < troot.element:
                return self.rsearch(troot.left,key)
            elif key > troot.element:
                return self.rsearch(troot.right,key)
        else: 
            return False
    
    def inorder(self, troot):
        if troot:
            self.inorder(troot.left)
            print(troot.element, end = ' ')
            self.inorder(troot.right)

In [325]:
b = Binary_search_tree()

In [326]:
b.insert(b.root, 50)
b.insert(b.root, 30)
b.insert(b.root, 80)
b.insert(b.root, 10)
b.insert(b.root, 40)
b.insert(b.root, 60)

In [327]:
b.inorder(b.root)

10 30 40 50 60 80 

In [331]:
b.rsearch(b.root,85)

False

In [1]:
#HEAP

In [84]:
class Heap:
    def __init__(self):
        self.maxsize = 10
        self.data = [-1] * self.maxsize
        self.csize = 0
    def __len__(self):
        return len(self.data)
    def isempty(self):
        return len(self.data) == 0
    def insert(self,e):
        if self.csize == self.maxsize:
            return 'No space'
        self.csize = self.csize + 1
        hi = self.csize #hi is the index 
        while hi > 1 and e > self.data[hi//2]:
            self.data[hi] = self.data[hi//2]
            hi = hi//2
        self.data[hi] = e
    def max(self):
        if self.csize == 0:
            return 'Heap is empty'
        return self.data[1]
    def deletemax(self):
        if self.csize == 0:
            return 'Heap is empty'
        e = self.data[1]
        self.data[1] = self.data[self.csize]
        self.data[self.csize] = -1
        self.csize = self.csize - 1
        i = 1
        j = i*2
        while j < self.csize:
            if self.data[j] < self.data[j+1]:
                j = j + 1
            if self.data[i] < self.data[j]:
                self.data[i], self.data[j] = self.data[j], self.data[i]
                i = j
                j = i * 2
            else:
                break
        return e

In [74]:
h = Heap()

In [75]:
h.insert(25)
h.insert(14)
h.insert(2)
h.insert(20)
h.insert(10)
h.insert(40)

In [76]:
h.data

[-1, 40, 20, 25, 14, 10, 2, -1, -1, -1]

In [77]:
import heapq as heap

In [78]:
lst = []
heap.heappush(lst,25)
heap.heappush(lst,14)
heap.heappush(lst,2)
heap.heappush(lst,10)
heap.heappush(lst,20)

In [79]:
print(lst)

[2, 10, 14, 25, 20]


In [80]:
e = heap.heapreplace(lst,1)

In [81]:
print(lst)

[1, 10, 14, 25, 20]


In [82]:
#Heap sort

In [110]:
def heapsort(A):
    H = Heap()
    n = len(A)
    for i in range(n):
        H.insert(A[i])
    k = n-1
    for i in range(H.csize):
        A[k] = H.deletemax()
        k = k - 1

In [111]:
mylist = [63, 250, 835, 947, 651, 28]
heapsort(mylist)

In [112]:
mylist

[28, 63, 250, 651, 835, 947]

In [3]:
#Hashing

In [102]:
#import linkedlist class
class Hash_chain:
    def __init__(self):
        self.hashtable_size = 10
        self.hashtable = [0] * self.hashtable_size
        for i in range(self.hashtable_size):
            self.hashtable[i] = LinkedList()
    def hashcode(self,key):
        return key % self.hashtable_size
    def insert(self,e):
        i = self.hashcode(e)
        self.hashtable[i].insertsorted(e)
    def search(self,key):
        i = self.hashcode(key)
        return self.hashtable[i].search(key)!= 'Not found'
    def display(self):
        for i in range(self.hashtable_size):
            print('[',i,']', end=' ')
            self.hashtable[i].display()

In [103]:
h = Hash_chain()       

In [104]:
h.insert(54)
h.insert(78)
h.insert(64)
h.insert(92)  
h.insert(94)
h.insert(88)

In [105]:
h.display()

[ 0 ] [ 1 ] [ 2 ] 92 [ 3 ] [ 4 ] 54 64 94 [ 5 ] [ 6 ] [ 7 ] [ 8 ] 78 88 [ 9 ] 

In [106]:
h.search(64)

True

In [107]:
h.hashtable[4].display()

54 64 94 

In [108]:
h.hashtable[4] == 0

False

In [78]:
#Hashing wiht linear probing

In [19]:
class HashLinearProbing:
    def __init__(self):
        self.hashtable_size = 10
        self.hashtable = [0] * self.hashtable_size
    def hashcode(self,key):
        return key % self.hashtable_size
    def lprobe(self, e):
        i = self.hashcode(e)
        j = 0
        while self.hashtable[(i+j) % self.hashtable_size] != 0:
            j = j + 1
        return (i + j) % self.hashtable_size
    def insert(self,e):
        i = self.hashcode(e)
        if self.hashtable[i] == 0:
            self.hashtable[i] = e
        else:
            i = self.lprobe(e)
            self.hashtable[i] = e
    def search(self,key):
        i = self.hashcode(key)
        j = 0
        while self.hashtable[(i+j) % self.hashtable_size] != key:
            if self.hashtable[(i+j) % self.hashtable_size] == 0:
                return False
            j = j + 1
        return True
    def display(self):
        print(self.hashtable)

In [20]:
ht = HashLinearProbing()

In [21]:
ht.insert(54)
ht.insert(78)
ht.insert(64)
ht.insert(92)
ht.insert(34)
ht.insert(86)
ht.insert(28)

In [27]:
ht.display()

[0, 0, 92, 0, 54, 64, 34, 86, 78, 28]


In [1]:
#Graphs with Adjacency Matrix Representation

In [21]:
import numpy as np
class Graph:
    def __init__(self,vertices):
        self.vertices = vertices
        self.adjmat = np.zeros((vertices,vertices))
    def insert_edge(self, u, v, x=1):
        self.adjmat[u][v] = x
    def remove_edge(self, u, v):
        self.adjmat[u][v] = 0
    def exist_edge(self,u,v):
        return self.adjmat[u][v] != 0
    def vertex_count(self):
        return self.vertices
    def edge_count(self):
        count=0
        for i in range(self.vertices):
            for j in range(self.vertices):
                if self.adjmat[i][j] != 0:
                    count += 1
        return count
    def vertices(self):
        for i in range(self.vertices):
            print(i, end=' ')
        print()
    def edges(self):
        for i in range(self.vertices):
            for j in range(self.vertices):
                if self.adjmat[i][j] != 0:
                    print(i,'--',j)
    def outdegree(self,v):
        count = 0
        for i in range(self.vertices):
            if self.adjmat[v][i] != 0:
                count += 1
        return count
    def indegree(self,v):
        count = 0
        for i in range(self.vertices):
            if self.adjmat[i][v] != 0:
                count = count + 1
        return count
    def display_adjmat(self):
        print(self.adjmat)
    def BFS(self,s):
        i = s
        

In [78]:
#Undirected graph:- (No beginning or end / no arrows between edges)

In [79]:
g = Graph(4)

In [80]:
g.display_adjmat()

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [81]:
g.vertex_count()

4

In [82]:
g.edge_count()

0

In [83]:
g.insert_edge(0,1)
g.insert_edge(0,2)
g.insert_edge(1,0)
g.insert_edge(1,2)
g.insert_edge(2,0)
g.insert_edge(2,1)
g.insert_edge(2,3)
g.insert_edge(3,2)

In [84]:
g.display_adjmat()

[[0. 1. 1. 0.]
 [1. 0. 1. 0.]
 [1. 1. 0. 1.]
 [0. 0. 1. 0.]]


In [85]:
g.edge_count()

8

In [86]:
g.edges() #i te j nested loop ch chalde pye aa

0 -- 1
0 -- 2
1 -- 0
1 -- 2
2 -- 0
2 -- 1
2 -- 3
3 -- 2


In [87]:
g.exist_edge(0,3)

False

In [88]:
g.indegree(2)

3

In [92]:
# In Weighted Undirected Graph (Weights are assigned to edges rest is same as undirected graph) 

In [93]:
#Directed graph:-

In [111]:
g = Graph(4)

In [112]:
g.display_adjmat()

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [113]:
g.insert_edge(0,1)
g.insert_edge(0,2)
g.insert_edge(1,2)
g.insert_edge(2,3)

In [114]:
g.display_adjmat()

[[0. 1. 1. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]]


In [117]:
g.edges()

0 -- 1
0 -- 2
1 -- 2
2 -- 3
